from App.models import db
db.create_all()
from App.models import Matches

#########################################################################################
matches0  = Matches(team1="Katar", team2="Ekwador", group="A")
db.session.add(matches0)
db.session.commit()
matches1  = Matches(team1="Senegal", team2="Holandia", group="A")
db.session.add(matches1)
db.session.commit()
matches2  = Matches(team1="Anglia", team2="Iran", group="B")
db.session.add(matches2)
db.session.commit()
matches3  = Matches(team1="USA", team2="Walia", group="B")
db.session.add(matches3)
db.session.commit()
matches4  = Matches(team1="Francja", team2="Australia", group="D")
db.session.add(matches4)
db.session.commit()
matches5  = Matches(team1="Dania", team2="Tunezja", group="D")
db.session.add(matches5)
db.session.commit()
matches6  = Matches(team1="Meksyk", team2="Polska", group="C")
db.session.add(matches6)
db.session.commit()
matches7  = Matches(team1="Argentyna", team2="Arabia Saudyjska", group="C")
db.session.add(matches7)
db.session.commit()
matches8  = Matches(team1="Belgia", team2="Kanada", group="F")
db.session.add(matches8)
db.session.commit()
matches9  = Matches(team1="Hiszpania", team2="Kostaryka", group="E")
db.session.add(matches9)
db.session.commit()
matches10 = Matches(team1="Niemcy", team2="Japonia", group="E")
db.session.add(matches10)
db.session.commit()
matches11 = Matches(team1="Maroko", team2="Chorwacja", group="F")
db.session.add(matches11)
db.session.commit()
matches12 = Matches(team1="Szwajcaria", team2="Kamerun", group="G")
db.session.add(matches12)
db.session.commit()
matches13 = Matches(team1="Urugwaj", team2="Korea Poludniowa", group="H")
db.session.add(matches13)
db.session.commit()
matches14 = Matches(team1="Portugalia", team2="Ghana", group="H")
db.session.add(matches14)
db.session.commit()
matches15 = Matches(team1="Brazylia", team2="Serbia", group="G")
db.session.add(matches15)
db.session.commit()
matches16 = Matches(team1="Walia", team2="Iran", group="B")
db.session.add(matches16)
db.session.commit()
matches17 = Matches(team1="Katar", team2="Senegal", group="A")
db.session.add(matches17)
db.session.commit()
matches18 = Matches(team1="Holandia", team2="Ekwador", group="A")
db.session.add(matches18)
db.session.commit()
matches19 = Matches(team1="Anglia", team2="USA", group="B")
db.session.add(matches19)
db.session.commit()
matches20 = Matches(team1="Tunezja", team2="Australia", group="D")
db.session.add(matches20)
db.session.commit()
matches21 = Matches(team1="Polska", team2="Arabia Saudyjska", group="C")
db.session.add(matches21)
db.session.commit()
matches22 = Matches(team1="Francja", team2="Dania", group="D")
db.session.add(matches22)
db.session.commit()
matches23 = Matches(team1="Argentyna", team2="Meksyk", group="C")
db.session.add(matches23)
db.session.commit()
matches24 = Matches(team1="Japonia", team2="Kostaryka", group="E")
db.session.add(matches24)
db.session.commit()
matches25 = Matches(team1="Belgia", team2="Maroko", group="F")
db.session.add(matches25)
db.session.commit()
matches26 = Matches(team1="Chorwacja", team2="Kanada", group="F")
db.session.add(matches26)
db.session.commit()
matches27 = Matches(team1="Hiszpania", team2="Niemcy", group="E")
db.session.add(matches27)
db.session.commit()
matches28 = Matches(team1="Kamerun", team2="Serbia", group="G")
db.session.add(matches28)
db.session.commit()
matches29 = Matches(team1="Korea Poludniowa", team2="Ghana", group="H")
db.session.add(matches29)
db.session.commit()
matches30 = Matches(team1="Brazylia", team2="Szwajcaria", group="G")
db.session.add(matches30)
db.session.commit()
matches31 = Matches(team1="Portugalia", team2="Urugwaj", group="H")
db.session.add(matches31)
db.session.commit()
matches32 = Matches(team1="Walia", team2="Anglia", group="B")
db.session.add(matches32)
db.session.commit()
matches33 = Matches(team1="Iran", team2="USA", group="B")
db.session.add(matches33)
db.session.commit()
matches34 = Matches(team1="Ekwador", team2="Senegal", group="A")
db.session.add(matches34)
db.session.commit()
matches35 = Matches(team1="Holandia", team2="Katar", group="A")
db.session.add(matches35)
db.session.commit()
matches36 = Matches(team1="Australia", team2="Dania", group="D")
db.session.add(matches36)
db.session.commit()
matches37 = Matches(team1="Tunezja", team2="Francja", group="D")
db.session.add(matches37)
db.session.commit()
matches38 = Matches(team1="Polska", team2="Argentyna", group="C")
db.session.add(matches38)
db.session.commit()
matches39 = Matches(team1="Arabia Saudyjska", team2="Meksyk", group="C")
db.session.add(matches39)
db.session.commit()
matches40 = Matches(team1="Chorwacja", team2="Belgia", group="F")
db.session.add(matches40)
db.session.commit()
matches41 = Matches(team1="Kanada", team2="Maroko", group="F")
db.session.add(matches41)
db.session.commit()
matches42 = Matches(team1="Japonia", team2="Hiszpania", group="E")
db.session.add(matches42)
db.session.commit()
matches43 = Matches(team1="Kostaryka", team2="Niemcy", group="E")
db.session.add(matches43)
db.session.commit()
matches44 = Matches(team1="Ghana", team2="Urugwaj", group="H")
db.session.add(matches44)
db.session.commit()
matches45 = Matches(team1="Korea Poludniowa", team2="Portugalia", group="H")
db.session.add(matches45)
db.session.commit()
matches46 = Matches(team1="Serbia", team2="Szwajcaria", group="G")
db.session.add(matches46)
db.session.commit()
matches47 = Matches(team1="Kamerun", team2="Brazylia", group="G")
db.session.add(matches47)
db.session.commit()
#########################################################################################
# matches = []
#####################       GRUPA A
# teams = ["Katar", "Ekwador", "Senegal", "Holandia"]

# matches0  = Matches(team1="Katar", team2="Ekwador", group="A")
# db.session.add(matches0)
# db.session.commit()
# matches1  = Matches(team1="Senegal", team2="Holandia", group="A")
# db.session.add(matches0)
# db.session.commit()
# matches17 = Matches(team1="Katar", team2="Senegal", group="A")
# db.session.add(matches0)
# db.session.commit()
# matches18 = Matches(team1="Holandia", team2="Ekwador", group="A")
# db.session.add(matches0)
# db.session.commit()
# matches34 = Matches(team1="Ekwador", team2="Senegal", group="A")
# db.session.add(matches0)
# db.session.commit()
# matches35 = Matches(team1="Holandia", team2="Katar", group="A")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA B
# teams = ["Anglia", "Iran", "USA", "Walia"]

# matches2  = Matches(team1="Anglia", team2="Iran", group="B")
# db.session.add(matches0)
# db.session.commit()
# matches3  = Matches(team1="USA", team2="Walia", group="B")
# db.session.add(matches0)
# db.session.commit()

# matches16 = Matches(team1="Walia", team2="Iran", group="B")
# db.session.add(matches0)
# db.session.commit()
# matches19 = Matches(team1="Anglia", team2="USA", group="B")
# db.session.add(matches0)
# db.session.commit()

# matches32 = Matches(team1="Walia", team2="Anglia", group="B")
# db.session.add(matches0)
# db.session.commit()
# matches33 = Matches(team1="Iran", team2="USA", group="B")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA C
# teams = ["Argentyna", "Arabia Saudyjska", "Meksyk", "Polska"]

# matches7  = Matches(team1="Argentyna", team2="Arabia Saudyjska", group="C")
# db.session.add(matches0)
# db.session.commit()
# matches6  = Matches(team1="Meksyk", team2="Polska", group="C")
# db.session.add(matches0)
# db.session.commit()

# matches21 = Matches(team1="Polska", team2="Arabia Saudyjska", group="C")
# db.session.add(matches0)
# db.session.commit()
# matches23 = Matches(team1="Argentyna", team2="Meksyk", group="C")
# db.session.add(matches0)
# db.session.commit()

# matches38 = Matches(team1="Polska", team2="Argentyna", group="C")
# db.session.add(matches0)
# db.session.commit()
# matches39 = Matches(team1="Arabia Saudyjska", team2="Meksyk", group="C")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA D
# teams = ["Dania", "Tunezja", "Francja", "Australia"]

# matches5  = Matches(team1="Dania", team2="Tunezja", group="D")
# db.session.add(matches0)
# db.session.commit()
# matches4  = Matches(team1="Francja", team2="Australia", group="D")
# db.session.add(matches0)
# db.session.commit()

# matches20 = Matches(team1="Tunezja", team2="Australia", group="D")
# db.session.add(matches0)
# db.session.commit()
# matches22 = Matches(team1="Francja", team2="Dania", group="D")
# db.session.add(matches0)
# db.session.commit()

# matches36 = Matches(team1="Australia", team2="Dania", group="D")
# db.session.add(matches0)
# db.session.commit()
# matches37 = Matches(team1="Tunezja", team2="Francja", group="D")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA E
# teams = ["Niemcy", "Japonia", "Hiszpania", "Kostaryka"]

# matches10 = Matches(team1="Niemcy", team2="Japonia", group="E")
# db.session.add(matches0)
# db.session.commit()
# matches9  = Matches(team1="Hiszpania", team2="Kostaryka", group="E")
# db.session.add(matches0)
# db.session.commit()

# matches24 = Matches(team1="Japonia", team2="Kostaryka", group="E")
# db.session.add(matches0)
# db.session.commit()
# matches27 = Matches(team1="Hiszpania", team2="Niemcy", group="E")
# db.session.add(matches0)
# db.session.commit()

# matches42 = Matches(team1="Japonia", team2="Hiszpania", group="E")
# db.session.add(matches0)
# db.session.commit()
# matches43 = Matches(team1="Kostaryka", team2="Niemcy", group="E")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA F
# teams = ["Maroko", "Chorwacja", "Belgia", "Kanada"]

# matches11 = Matches(team1="Maroko", team2="Chorwacja", group="F")
# db.session.add(matches0)
# db.session.commit()
# matches8  = Matches(team1="Belgia", team2="Kanada", group="F")
# db.session.add(matches0)
# db.session.commit()

# matches25 = Matches(team1="Belgia", team2="Maroko", group="F")
# db.session.add(matches0)
# db.session.commit()
# matches26 = Matches(team1="Chorwacja", team2="Kanada", group="F")
# db.session.add(matches0)
# db.session.commit()

# matches40 = Matches(team1="Chorwacja", team2="Belgia", group="F")
# db.session.add(matches0)
# db.session.commit()
# matches41 = Matches(team1="Kanada", team2="Maroko", group="F")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA G
# teams = ["Szwajcaria", "Kamerun", "Brazylia", "Serbia"]

# matches12 = Matches(team1="Szwajcaria", team2="Kamerun", group="G")
# db.session.add(matches0)
# db.session.commit()
# matches15 = Matches(team1="Brazylia", team2="Serbia", group="G")
# db.session.add(matches0)
# db.session.commit()

# matches28 = Matches(team1="Kamerun", team2="Serbia", group="G")
# db.session.add(matches0)
# db.session.commit()
# matches30 = Matches(team1="Brazylia", team2="Szwajcaria", group="G")
# db.session.add(matches0)
# db.session.commit()

# matches46 = Matches(team1="Serbia", team2="Szwajcaria", group="G")
# db.session.add(matches0)
# db.session.commit()
# matches47 = Matches(team1="Kamerun", team2="Brazylia", group="G")
# db.session.add(matches0)
# db.session.commit()

# #####################       GRUPA H
# teams = ["Urugwaj", "Korea Poludniowa", "Portugalia", "Ghana"]

# matches13 = Matches(team1="Urugwaj", team2="Korea Poludniowa", group="H")
# db.session.add(matches0)
# db.session.commit()
# matches14 = Matches(team1="Portugalia", team2="Ghana", group="H")
# db.session.add(matches0)
# db.session.commit()

# matches29 = Matches(team1="Korea Poludniowa", team2="Ghana", group="H")
# db.session.add(matches0)
# db.session.commit()
# matches31 = Matches(team1="Portugalia", team2="Urugwaj", group="H")
# db.session.add(matches0)
# db.session.commit()

# matches44 = Matches(team1="Ghana", team2="Urugwaj", group="H")
# db.session.add(matches0)
# db.session.commit()
# matches45 = Matches(team1="Korea Poludniowa", team2="Portugalia", group="H")
# db.session.add(matches0)
# db.session.commit()

# # for i in range(46, group="A")
# db.session.add(matches0)
# db.session.commit()# :
# #     db.session.add(matchesi]
# #     db.session.commit(, group="A")
# db.session.add(matches0)
# db.session.commit()
    